server:
  port: 8089
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/${sb3_jwt_role_051123}?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: Spring Boot 3 Authentication and Authorization With JWT

# GUID/UUID online generator
jwt.secret.sign.key: ${EF6E0258-E0B0-4A5D-889D-E2912F5897B5}
